# 基础配置文件
server:
  servlet:
    context-path: /v1     # 应用路径，可以通过设置路径来控制版本
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    throw-exception-if-no-handler-found: true     # 接口404时抛出异常
  resources:
    add-mappings: false
  redis:
    database: 12
    host: 192.168.2.169
    password:
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-idle: 200
        min-idle: 100
        max-wait: 1000
    timeout: 3000
  datasource: #Druid 连接池通用配置
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.2.169:3306/karl?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: karl     # 数据库账号
      password: karl     # 数据库密码
  devtools:
    restart:
      enabled: true     # 开启热更新
  flyway:
    enabled: true
    clean-disabled: true
    placeholder-replacement: false
    validate-on-migrate: false
    baseline-on-migrate: true
    url: ${spring.datasource.druid.url}
    user: ${spring.datasource.druid.username}
    password: ${spring.datasource.druid.password}
    table: T_SCHEMA_VERSION
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
mybatis:
  table:
    auto: add
  #   create  时，系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
  #   update  时，系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
  #   none    时，系统不做任何处理。
  #   add     时，新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除
  model:
    pack: com.karl.core.entity,com.karl.module.entity
  database:
    type: mysql

# 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY: true
# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true
# dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_URL: /api/
# dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/
# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql