# 基础配置文件
server:
  servlet:
    context-path: /v1     # 应用路径，可以通过设置路径来控制版本
  tomcat:
    uri-encoding: UTF-8
  port: 80

spring:
  mvc:
    throw-exception-if-no-handler-found: true     # 接口404时抛出异常
  resources:
    add-mappings: false
  redis:
    database: 11
    host: 192.168.2.169
    password:
    port: 5379
    jedis:
      pool:
        max-active: 200
        max-idle: 200
        min-idle: 100
        max-wait: PT5M
    timeout: PT5M

  datasource: #Druid 连接池通用配置
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.2.169:3306/karl2?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: karl     # 数据库账号
      password: karl     # 数据库密码
  devtools:
    restart:
      enabled: true     # 开启热更新
  flyway:
    enabled: true
    clean-disabled: true
    placeholder-replacement: false
    validate-on-migrate: false
    baseline-on-migrate: true
    url: ${spring.datasource.druid.url}
    user: ${spring.datasource.druid.username}
    password: ${spring.datasource.druid.password}
    table: SCHEMA_VERSION

#mybatis-plus:
#  #  configuration:
#  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapperLocations: classpath*:com/karl/**/mapper/*.xml

mybatis:
  table:
    auto: add
  #   create  时，系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据。
  #   update  时，系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
  #   none    时，系统不做任何处理。
  #   add     时，新增表/新增字段/新增索引/新增唯一约束的功能，不做做修改和删除
  model:
    pack: com.karl.core.entity,com.karl.module.entity
  database:
    type: mysql

logging:
  level:
    root: info